//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MirokuExample.DBFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class EdmProduct
    {
        public int ProductId { get; set; }
        public string Name { get; set; }
        public string CategoryID { get; set; }
    
        public virtual EdmCategory EdmCategory { get; set; }
    }
}
