//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MirokuExample.DBFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hello
    {
        public long Hello1 { get; set; }
    }
}
